apiVersion: v1
entries:
  maesh:
  - apiVersion: v1
    appVersion: v0.7.0
    created: "2019-10-23T16:03:24.098095065Z"
    description: Maesh - Simpler Service Mesh
    digest: 338335af4b6448562678213789ac405a798aa02053ab883aaae3a001bee82a3a
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.8.tgz
    version: 0.0.8
  - apiVersion: v1
    appVersion: v0.6.0
    created: "2019-10-23T16:03:24.097075197Z"
    description: Maesh - Simpler Service Mesh
    digest: 29710358d2d709c6e1fc8b26e441c8f3b09d7482a4ca4507fd313e48633c18b4
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.7.tgz
    version: 0.0.7
  - apiVersion: v1
    appVersion: v0.5.0
    created: "2019-10-23T16:03:24.096017071Z"
    description: Maesh - Simpler Service Mesh
    digest: 9c55f8d3aeb837c31309fc947862ee0bbb64342116e63b746d0960a74e867cca
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.6.tgz
    version: 0.0.6
  - apiVersion: v1
    appVersion: v0.4.0
    created: "2019-10-23T16:03:24.094890553Z"
    description: Maesh - Simpler Service Mesh
    digest: 12d970fe9a44d2d732b64cc0aa0065f443ee3ed895189629dcb4568552e9054f
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.5.tgz
    version: 0.0.5
  - apiVersion: v1
    appVersion: v0.3.0
    created: "2019-10-23T16:03:24.093812892Z"
    description: Maesh - Simpler Service Mesh
    digest: 076419c25f246905f54ef1e62c6d456314bf11861614702fd537b01dc18d4033
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.4.tgz
    version: 0.0.4
  - apiVersion: v1
    appVersion: v0.2.1
    created: "2019-10-23T16:03:24.092514436Z"
    description: Maesh - Simpler Service Mesh
    digest: 7b5f046932093fee5f210ac5dd2357eaf51c81b3de38e8556d5bb9a6ff8bacc7
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.3.tgz
    version: 0.0.3
  - apiVersion: v1
    appVersion: v0.1.0
    created: "2019-10-23T16:03:24.088109325Z"
    description: Maesh - Simpler Service Mesh
    digest: 14a1f2c5dc31e7bf6a16579dc07628d6b25968d255f36c1598418722495ca484
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.1.tgz
    version: 0.0.1
  - apiVersion: v1
    appVersion: v0.2.0
    created: "2019-10-23T16:03:24.090482099Z"
    description: Maesh - Simpler Service Mesh
    digest: fe4d306f4b3da42416f1999dad8fd4356fab60a1aab78e0f0d5bf6ffc1ae8bfe
    engine: gotpl
    home: https://containo.us/
    icon: https://avatars0.githubusercontent.com/u/16349663?s=200&v=4
    keywords:
    - traefik
    - mesh
    maintainers:
    - email: emile@vauge.com
      name: emilevauge
    - email: daniel@containo.us
      name: dtomcej
    - email: michael@containo.us
      name: mmatur
    name: maesh
    urls:
    - maesh-0.0.2.tgz
    version: 0.0.1
generated: "2019-10-23T16:03:24.086745028Z"
